version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: jigsawjunction-postgres
    environment:
      POSTGRES_DB: jigsawjunction
      POSTGRES_USER: jigsawuser
      POSTGRES_PASSWORD: jigsawpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jigsawuser -d jigsawjunction"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: jigsawjunction-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # JigsawJunction Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: jigsawjunction-app
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://jigsawuser:jigsawpassword@postgres:5432/jigsawjunction
      SESSION_SECRET: jigsawjunction-super-secret-session-key-2024-production-ready-64-chars-long
      JWT_SECRET: jigsawjunction-super-secret-jwt-key-2024-production-ready-64-chars-long
      CORS_ORIGIN: http://localhost:3000
      FRONTEND_URL: http://localhost:3000
      GOOGLE_DRIVE_FOLDER_ID: 1t6EIYP_O-no6phutgcPC4Tk7Kopdpw5A
      STORAGE_TYPE: google-drive
      MAX_FILE_SIZE: 5242880
      API_RATE_LIMIT: 50
      AUTH_RATE_LIMIT: 3
      UPLOAD_RATE_LIMIT: 5
      SESSION_TIMEOUT: 86400000
      SESSION_CLEANUP_INTERVAL: 3600000
      FORCE_HTTPS: false
      STRICT_TRANSPORT_SECURITY: false
      CONTENT_SECURITY_POLICY: true
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./google-drive-service-account.json:/app/google-drive-service-account.json:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: jigsawjunction-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:
