module.exports = {
  apps: [
    {
      name: 'jigsawjunction',
      script: 'dist/server/index.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 5000
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5000,
        DATABASE_URL: 'postgresql://user:password@host:5432/jigsawjunction',
        SESSION_SECRET: 'jigsawjunction-super-secret-session-key-2024-production-ready-64-chars-long',
        JWT_SECRET: 'jigsawjunction-super-secret-jwt-key-2024-production-ready-64-chars-long',
        CORS_ORIGIN: 'https://your-actual-domain.com',
        FRONTEND_URL: 'https://your-actual-domain.com',
        GOOGLE_DRIVE_FOLDER_ID: '1t6EIYP_O-no6phutgcPC4Tk7Kopdpw5A',
        STORAGE_TYPE: 'google-drive',
        MAX_FILE_SIZE: 5242880,
        API_RATE_LIMIT: 50,
        AUTH_RATE_LIMIT: 3,
        UPLOAD_RATE_LIMIT: 5,
        SESSION_TIMEOUT: 86400000,
        SESSION_CLEANUP_INTERVAL: 3600000,
        FORCE_HTTPS: true,
        STRICT_TRANSPORT_SECURITY: true,
        CONTENT_SECURITY_POLICY: true
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_file: './logs/combined.log',
      time: true,
      max_memory_restart: '1G',
      node_args: '--max-old-space-size=1024',
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'uploads'],
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      source_map_support: true,
      disable_source_map_support: false,
      increment_var: 'PORT',
      instance_var: 'INSTANCE_ID',
      pid_file: './pids/app.pid',
      write_file: './pids/app.pid',
      kill_retry_time: 100,
      listen_timeout: 8000,
      shutdown_with_message: true,
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      source_map_support: true,
      disable_source_map_support: false,
      increment_var: 'PORT',
      instance_var: 'INSTANCE_ID',
      pid_file: './pids/app.pid',
      write_file: './pids/app.pid',
      kill_retry_time: 100,
      listen_timeout: 8000,
      shutdown_with_message: true
    }
  ],

  deploy: {
    production: {
      user: 'deploy',
      host: 'your-server.com',
      ref: 'origin/main',
      repo: 'git@github.com:yourusername/jigsawjunction.git',
      path: '/var/www/jigsawjunction',
      'pre-deploy-local': '',
      'post-deploy': 'npm install && npm run build && pm2 reload ecosystem.config.js --env production',
      'pre-setup': ''
    }
  }
};
